**Analyse der erstellten Daten:**

In [5]:
import json
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style="whitegrid")

In [6]:
RESULT_FILE = "results/results_direct_gpt-5.1.json"

with open(RESULT_FILE, "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)

print("Number of tasks:", len(df))
df.head()

Number of tasks: 100

,id,type,question,ground_truth,model,strategy,raw_output,parsed_prediction,correct,latency
0,1,countVowels,Count the vowels in the string: dgfdsfhuipoai,5,gpt-5.1,direct,5,5,True,1.403705
1,2,countVowels,Count the vowels in the string: oihjsahsaud,5,gpt-5.1,direct,6,6,False,0.908747
2,3,countVowels,Count the vowels in the string: aufnbejtkfi,4,gpt-5.1,direct,3,3,False,1.665074
3,4,countVowels,Count the vowels in the string: hkhgfdhybnijg,1,gpt-5.1,direct,1,1,True,1.001404
4,5,countConsonants,Count the Consonants in the string: hgrwopjuia,6,gpt-5.1,direct,7,7,False,0.853332

In [7]:
accuracy = df["correct"].mean()

print("Overall Accuracy:", round(accuracy * 100, 2), "%")

Overall Accuracy: 51.0 %

In [8]:
strategy_acc = df.groupby("strategy")["correct"].mean().reset_index()

strategy_acc

  strategy  correct
0   direct     0.51